export const people = [
	'David',
	'JuanMa',
	'Luis',
	'Mario',
	'Michael',
	'Michal',
	'Pablo',
	'Reyes',
	'Cristian'
]

export const topics = [
	'Hiking',
	'Indiana Jones',
	'Jurassic Park - the movie',
	'Mars',
	'Marsupials',
	'Mojitos',
	'Namibia',
	'Neil Armstrong',
	'Norway',
	'Orang Utans',
	'Parque de El Retiro, Madrid',
	'Penelope Cruz',
	'Pickup Trucks',
	'Pirates',
	'Rafael Nadal',
	'Rice',
	'Ronald Reagan',
	'Shoes',
	'Singapore',
	'Skyscrapers',
	'Space Exploration',
	'Spaghetti Westerns',
	'Submarines',
	'Texas',
	'The Age of Steam',
	'The Clarinet',
	'The Equator',
	'The Eurovision Song Contest',
	'The Great Barrier Reef',
	'The Human Brain',
	'The International Banking System',
	'The Nile',
	'The Ocean',
	'The Panama Canal',
	'The Titanic',
	'The Tour de France',
	'Tom Hanks',
	'Vampires',
	'Venice',
	'Waterfalls',
	'Wine',
	'Woody Allen',
	'Yosemite National Park',
	'Zanzibar',
]